In [1]:
import numpy as np

In [2]:
x = np.array([1.0, 2.0, 3.0])

In [3]:
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array([2.0, 4.0, 6.0])

In [6]:
x + y

array([3., 6., 9.])

In [7]:
x * y # 원소별 곱셈 (element-wise product)

array([ 2.,  8., 18.])

In [8]:
x / y # 원소별 나눗셈

array([0.5, 0.5, 0.5])

In [9]:
x / 2.0 # broadcast : numpy 배열 + 수치 하나로 연산 수행

array([0.5, 1. , 1.5])

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

In [12]:
X = np.array([[51, 55], [14, 19], [0, 4]])

In [14]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [15]:
X[np.array([0, 2, 4])] # 원소 번호 입력해서 얻을 수 있음

array([51, 14,  0])

In [16]:
X > 15 # 특정 조건을 만족하는지 확인 가능

array([ True,  True, False,  True, False, False])

In [17]:
X[X>15] # 특정 조건을 만족하는 원소만 출력

array([51, 55, 19])