In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [3]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [5]:
# Default values, in case of empty columns. Also specifies the type of the decoded result
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [6]:
# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10) # X data, Y data, 한번에 10개씩 가져오기

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [7]:
#placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [8]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session
sess = tf.Session()

#Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

In [12]:
#Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [13]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) # train_?_batch도 tensor이니까 세션으로 실행시킨다, 펌프질을 해서 데이터를 가져온다
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict = {X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        
coord.request_stop()
coord.join(threads)

0 Cost:  1749.4633 
Prediction:
 [[101.581955]
 [134.76744 ]
 [125.95825 ]
 [142.26735 ]
 [101.46921 ]
 [ 83.62068 ]
 [110.10094 ]
 [ 86.41441 ]
 [134.83586 ]
 [136.91832 ]]
10 Cost:  71.93071 
Prediction:
 [[146.21059]
 [188.36087]
 [178.7897 ]
 [199.78993]
 [142.34377]
 [113.72748]
 [153.14938]
 [118.31641]
 [184.89388]
 [183.2472 ]]
20 Cost:  74.3062 
Prediction:
 [[146.54297 ]
 [188.706   ]
 [179.15915 ]
 [200.1757  ]
 [142.6071  ]
 [113.88972 ]
 [153.42879 ]
 [118.512054]
 [185.18356 ]
 [183.47403 ]]
30 Cost:  73.7134 
Prediction:
 [[146.57628 ]
 [188.69182 ]
 [179.17448 ]
 [200.1759  ]
 [142.59642 ]
 [113.85005 ]
 [153.4196  ]
 [118.493805]
 [185.1376  ]
 [183.39015 ]]
40 Cost:  73.10559 
Prediction:
 [[146.60745]
 [188.67532]
 [179.18738]
 [200.17354]
 [142.58398]
 [113.80923]
 [153.40854]
 [118.47421]
 [185.0896 ]
 [183.30458]]
50 Cost:  72.50274 
Prediction:
 [[146.63841]
 [188.65886]
 [179.20016]
 [200.17113]
 [142.57156]
 [113.76856]
 [153.39749]
 [118.45467]
 [185.04178]
 [

500 Cost:  50.289883 
Prediction:
 [[147.89542 ]
 [187.99265 ]
 [179.72017 ]
 [200.07391 ]
 [142.0696  ]
 [112.119736]
 [152.94841 ]
 [117.660194]
 [183.10316 ]
 [179.76195 ]]
510 Cost:  49.8908 
Prediction:
 [[147.92049]
 [187.97937]
 [179.73055]
 [200.07196]
 [142.05962]
 [112.08682]
 [152.93942]
 [117.64428]
 [183.06445]
 [179.69292]]
520 Cost:  49.495342 
Prediction:
 [[147.94547 ]
 [187.96616 ]
 [179.74089 ]
 [200.07004 ]
 [142.04967 ]
 [112.05406 ]
 [152.93047 ]
 [117.628426]
 [183.02596 ]
 [179.6242  ]]
530 Cost:  49.103382 
Prediction:
 [[147.97034 ]
 [187.953   ]
 [179.75119 ]
 [200.0681  ]
 [142.03978 ]
 [112.021454]
 [152.92157 ]
 [117.612656]
 [182.98764 ]
 [179.5558  ]]
540 Cost:  48.714912 
Prediction:
 [[147.99507 ]
 [187.93991 ]
 [179.76143 ]
 [200.0662  ]
 [142.02992 ]
 [111.989006]
 [152.91269 ]
 [117.59695 ]
 [182.94946 ]
 [179.48772 ]]
550 Cost:  48.329903 
Prediction:
 [[148.0197  ]
 [187.92688 ]
 [179.77162 ]
 [200.06429 ]
 [142.02013 ]
 [111.9567  ]
 [152.90385 ]

1110 Cost:  31.432934 
Prediction:
 [[149.23251 ]
 [187.28557 ]
 [180.27425 ]
 [199.96962 ]
 [141.53879 ]
 [110.365326]
 [152.46674 ]
 [116.807434]
 [181.0405  ]
 [176.07968 ]]
1120 Cost:  31.201214 
Prediction:
 [[149.25145]
 [187.27559]
 [180.2821 ]
 [199.96814]
 [141.5313 ]
 [110.34047]
 [152.45988]
 [116.79527]
 [181.01128]
 [176.02748]]
1130 Cost:  30.971497 
Prediction:
 [[149.27032]
 [187.26562]
 [180.28993]
 [199.96666]
 [141.52385]
 [110.31573]
 [152.45306]
 [116.78318]
 [180.9822 ]
 [175.97551]]
1140 Cost:  30.743774 
Prediction:
 [[149.28906]
 [187.25572]
 [180.2977 ]
 [199.96518]
 [141.51643]
 [110.29111]
 [152.44624]
 [116.77113]
 [180.95322]
 [175.92377]]
1150 Cost:  30.518177 
Prediction:
 [[149.30775]
 [187.24586]
 [180.30548]
 [199.96373]
 [141.50905]
 [110.26659]
 [152.43948]
 [116.75915]
 [180.92442]
 [175.87228]]
1160 Cost:  30.294582 
Prediction:
 [[149.32637]
 [187.23605]
 [180.3132 ]
 [199.96228]
 [141.50171]
 [110.24219]
 [152.43275]
 [116.7472 ]
 [180.89575]
 [

1680 Cost:  21.012035 
Prediction:
 [[150.18425 ]
 [186.7838  ]
 [180.66948 ]
 [199.89462 ]
 [141.16383 ]
 [109.11616 ]
 [152.1203  ]
 [116.193565]
 [179.57195 ]
 [173.45465 ]]
1690 Cost:  20.87199 
Prediction:
 [[150.1988  ]
 [186.77614 ]
 [180.67554 ]
 [199.89346 ]
 [141.15813 ]
 [109.097046]
 [152.11497 ]
 [116.18412 ]
 [179.54947 ]
 [173.41444 ]]
1700 Cost:  20.733156 
Prediction:
 [[150.21332]
 [186.76851]
 [180.68158]
 [199.89233]
 [141.15245]
 [109.078  ]
 [152.10968]
 [116.1747 ]
 [179.5271 ]
 [173.37442]]
1710 Cost:  20.595507 
Prediction:
 [[150.22775]
 [186.76091]
 [180.68758]
 [199.89119]
 [141.14677]
 [109.05905]
 [152.10439]
 [116.16532]
 [179.50482]
 [173.33458]]
1720 Cost:  20.459068 
Prediction:
 [[150.24211]
 [186.75334]
 [180.69356]
 [199.89005]
 [141.14114]
 [109.04019]
 [152.0991 ]
 [116.156  ]
 [179.48265]
 [173.29492]]
1730 Cost:  20.323837 
Prediction:
 [[150.25641 ]
 [186.7458  ]
 [180.69948 ]
 [199.8889  ]
 [141.13553 ]
 [109.02142 ]
 [152.09389 ]
 [116.146706