In [6]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
tf.set_random_seed(777) # for reproducibility

Instructions for updating:
non-resource variables are not supported in the long term


In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=",", dtype=np.float32) # 파일 읽어오기
x_data = xy[:, 0:-1] # n개의 행을 전부 다 가져오고, 그 행들에서 0부터 마지막 값 제외한 것까지 가져오기
y_data = xy[:, [-1]] # n개의 행을 전부 다 가져오는데, 마지막 값만 y로 치겠다

In [8]:
# Make sure the shape and data are ok
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [9]:
# placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [10]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [12]:
# Simplified cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [13]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [14]:
# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
# Set up feed_dict variables inside the loop
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  21027.0 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.29302  ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347937 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189459 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084753 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.98636  ]]
10 Cost:  95.97638 
Prediction:
 [[157.11061]
 [183.99281]
 [184.06302]
 [196.52916]
 [142.46275]
 [ 98.59757]
 [142.77237]
 [ 99.8778 ]
 [166.13174]
 [144.8915 ]
 [140.14996]
 [134.61137]
 [194.05148]
 [166.64043]
 [142.28706]
 [183.433  ]
 [161.97668]
 [169.89073]
 [186.37148]
 [166.61378]
 [168.04633]
 [169.14368]
 [161.75206]
 [167.4886 ]
 [193.25116]]
20 Cost:  94.257286 
Prediction:
 [[158.01505]
 [185.11972]
 [185.15114]
 [197.73495]
 [143.31499]
 [ 99.26259]
 [143.69463]
 [100.58784]
 [167.21954]
 [145.94849]
 [141.02907]
 [135.50375]
 [195.15508]
 [167.5308 ]
 [143.2218 ]
 [184.59265]
 [162.81183]
 [17

280 Cost:  77.51451 
Prediction:
 [[157.31897]
 [185.2471 ]
 [184.73795]
 [197.79527]
 [143.23071]
 [100.10071]
 [144.2284 ]
 [101.63812]
 [168.18582]
 [148.05789]
 [141.30655]
 [136.3985 ]
 [194.22214]
 [166.08975]
 [143.95853]
 [185.11938]
 [161.1187 ]
 [171.74097]
 [186.2951 ]
 [166.53326]
 [169.7088 ]
 [170.77478]
 [163.10054]
 [166.47028]
 [194.14297]]
290 Cost:  76.94079 
Prediction:
 [[157.29373]
 [185.25119]
 [184.72273]
 [197.79723]
 [143.22708]
 [100.13067]
 [144.2478 ]
 [101.67655]
 [168.22029]
 [148.1339 ]
 [141.31647]
 [136.43054]
 [194.188  ]
 [166.03716]
 [143.9852 ]
 [185.13803]
 [161.05673]
 [171.76799]
 [186.2543 ]
 [166.49641]
 [169.7299 ]
 [170.79453]
 [163.11243]
 [166.40192]
 [194.13306]]
300 Cost:  76.3718 
Prediction:
 [[157.26862 ]
 [185.25523 ]
 [184.70755 ]
 [197.79918 ]
 [143.22342 ]
 [100.160484]
 [144.26712 ]
 [101.71485 ]
 [168.25456 ]
 [148.20955 ]
 [141.32631 ]
 [136.46245 ]
 [194.15399 ]
 [165.98474 ]
 [144.01178 ]
 [185.15657 ]
 [160.99503 ]
 [171.794

550 Cost:  63.591167 
Prediction:
 [[156.68054]
 [185.34528]
 [184.3497 ]
 [197.84714]
 [143.12906]
 [100.85953]
 [144.73051]
 [102.63244]
 [169.05846]
 [149.99303]
 [141.56075]
 [137.21312]
 [193.34966]
 [164.74327]
 [144.64478]
 [185.59166]
 [159.52827]
 [172.4429 ]
 [185.25453]
 [165.59477]
 [170.25288]
 [171.27512]
 [163.4105 ]
 [164.72742]
 [193.88492]]
560 Cost:  63.133366 
Prediction:
 [[156.65854 ]
 [185.34845 ]
 [184.3362  ]
 [197.849   ]
 [143.12517 ]
 [100.88572 ]
 [144.74826 ]
 [102.667595]
 [169.08856 ]
 [150.06023 ]
 [141.56966 ]
 [137.24135 ]
 [193.31924 ]
 [164.69623 ]
 [144.66888 ]
 [185.60794 ]
 [159.47253 ]
 [172.46783 ]
 [185.21832 ]
 [165.5622  ]
 [170.27206 ]
 [171.2924  ]
 [163.42155 ]
 [164.66681 ]
 [193.87573 ]]
570 Cost:  62.679394 
Prediction:
 [[156.63663 ]
 [185.3516  ]
 [184.32275 ]
 [197.85088 ]
 [143.12128 ]
 [100.911766]
 [144.76598 ]
 [102.70262 ]
 [169.11852 ]
 [150.12712 ]
 [141.57855 ]
 [137.26942 ]
 [193.28896 ]
 [164.64938 ]
 [144.6929  ]
 [185.62

850 Cost:  51.38715 
Prediction:
 [[156.06676 ]
 [185.42789 ]
 [183.96986 ]
 [197.90224 ]
 [143.00917 ]
 [101.590485]
 [145.23897 ]
 [103.63822 ]
 [169.89882 ]
 [151.88116 ]
 [141.81363 ]
 [138.00426 ]
 [192.49113 ]
 [163.41373 ]
 [145.33    ]
 [186.04669 ]
 [157.94717 ]
 [173.1592  ]
 [184.23514 ]
 [164.67906 ]
 [170.8     ]
 [171.758   ]
 [163.7289  ]
 [163.02187 ]
 [193.62057 ]]
860 Cost:  51.030396 
Prediction:
 [[156.04787]
 [185.4302 ]
 [183.95807]
 [197.90404]
 [143.00507]
 [101.613  ]
 [145.25508]
 [103.67006]
 [169.9247 ]
 [151.93976]
 [141.82156]
 [138.02873]
 [192.46437]
 [163.37221]
 [145.35153]
 [186.06068]
 [157.89757]
 [173.18199]
 [184.20343]
 [164.65065]
 [170.81728]
 [171.77287]
 [163.73907]
 [162.96884]
 [193.61215]]
870 Cost:  50.676586 
Prediction:
 [[156.02908]
 [185.43251]
 [183.94632]
 [197.90582]
 [143.00096]
 [101.6354 ]
 [145.27112]
 [103.70181]
 [169.95045]
 [151.99808]
 [141.82947]
 [138.0531 ]
 [192.43771]
 [163.33083]
 [145.373  ]
 [186.07465]
 [157.84818

1160 Cost:  41.589813 
Prediction:
 [[155.52441]
 [185.4886 ]
 [183.62743]
 [197.95647]
 [142.88011]
 [102.23785]
 [145.71503]
 [104.57888]
 [170.64284]
 [153.57838]
 [142.04594]
 [138.71158]
 [191.71199]
 [162.2025 ]
 [145.96198]
 [186.44975]
 [156.4958 ]
 [173.83531]
 [183.31465]
 [163.85593]
 [171.3085 ]
 [172.18655]
 [164.0315 ]
 [161.48361]
 [193.3701 ]]
1170 Cost:  41.313564 
Prediction:
 [[155.50833]
 [185.49017]
 [183.61714]
 [197.95816]
 [142.87589]
 [102.25708]
 [145.72961]
 [104.60767]
 [170.66493]
 [153.62923]
 [142.05298]
 [138.73271]
 [191.68854]
 [162.16594]
 [145.98117]
 [186.46173]
 [156.45183]
 [173.85611]
 [183.28702]
 [163.83127]
 [171.324  ]
 [172.19931]
 [164.04082]
 [161.43744]
 [193.36238]]
1180 Cost:  41.03954 
Prediction:
 [[155.49232 ]
 [185.49174 ]
 [183.60692 ]
 [197.95987 ]
 [142.87166 ]
 [102.2762  ]
 [145.74414 ]
 [104.636375]
 [170.68692 ]
 [153.67984 ]
 [142.06    ]
 [138.75372 ]
 [191.66516 ]
 [162.12953 ]
 [146.0003  ]
 [186.47363 ]
 [156.408   ]
 [1

1420 Cost:  35.09445 
Prediction:
 [[155.13223]
 [185.5233 ]
 [183.37468]
 [197.99979]
 [142.76947]
 [102.70709]
 [146.07939]
 [105.29804]
 [171.18199]
 [154.82736]
 [142.22058]
 [139.22928]
 [191.13315]
 [161.29924]
 [146.43886]
 [186.742  ]
 [155.40558]
 [174.35664]
 [182.63419]
 [163.25018]
 [171.695  ]
 [172.4979 ]
 [164.26622]
 [160.34782]
 [193.17628]]
1430 Cost:  34.871178 
Prediction:
 [[155.1182  ]
 [185.52437 ]
 [183.36554 ]
 [198.00142 ]
 [142.7652  ]
 [102.723915]
 [146.0928  ]
 [105.32451 ]
 [171.20132 ]
 [154.8725  ]
 [142.22697 ]
 [139.24796 ]
 [191.11214 ]
 [161.2664  ]
 [146.45631 ]
 [186.75247 ]
 [155.36578 ]
 [174.3759  ]
 [182.60954 ]
 [163.2283  ]
 [171.7092  ]
 [172.50908 ]
 [164.27492 ]
 [160.3067  ]
 [193.16911 ]]
1440 Cost:  34.649708 
Prediction:
 [[155.10422]
 [185.52542]
 [183.35645]
 [198.00304]
 [142.76093]
 [102.74065]
 [146.10619]
 [105.35089]
 [171.22057]
 [154.91742]
 [142.23332]
 [139.26653]
 [191.09122]
 [161.23369]
 [146.47371]
 [186.76292]
 [155.32

1740 Cost:  28.77783 
Prediction:
 [[154.71758]
 [185.54909]
 [183.10141]
 [198.05046]
 [142.63203]
 [103.20452]
 [146.48834]
 [106.10441]
 [171.75334]
 [156.17346]
 [142.41309]
 [139.78398]
 [190.50291]
 [160.31194]
 [146.96657]
 [187.0519 ]
 [154.20479]
 [174.94608]
 [181.89722]
 [162.5973 ]
 [172.12587]
 [172.82878]
 [164.5332 ]
 [159.11928]
 [192.95638]]
1750 Cost:  28.605644 
Prediction:
 [[154.70572 ]
 [185.54964 ]
 [183.09348 ]
 [198.052   ]
 [142.62773 ]
 [103.218765]
 [146.50047 ]
 [106.128296]
 [171.7697  ]
 [156.21242 ]
 [142.41873 ]
 [139.79999 ]
 [190.48457 ]
 [160.28311 ]
 [146.98209 ]
 [187.06078 ]
 [154.16959 ]
 [174.96362 ]
 [181.87582 ]
 [162.57843 ]
 [172.13858 ]
 [172.83827 ]
 [164.5412  ]
 [159.08365 ]
 [192.94983 ]]
1760 Cost:  28.43486 
Prediction:
 [[154.69392]
 [185.55017]
 [183.08559]
 [198.05356]
 [142.62343]
 [103.23295]
 [146.51256]
 [106.15212]
 [171.78598]
 [156.2512 ]
 [142.42436]
 [139.8159 ]
 [190.46631]
 [160.25443]
 [146.99754]
 [187.06961]
 [154.134

In [15]:
# Ask my score 학습한 것을 바탕으로 예측해보기
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[181.73276]]
Other scores will be  [[145.86266]
 [187.23131]]
