In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t.ndim) # rank : 2 (차원) ( '[' 이게 몇 개냐에 따라 결정된다
print(t.shape) # shape : (4, 3)

2
(4, 3)


In [11]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval(session=tf.Session()) # shape: [1, 2, 3, 4] 가장 안 쪽의 것부터 바깥까지 세어서 나오기
# rank는 4, shape의 길이는 rank의 크기만큼
# Axis? 축(0부터 n-1까지)

array([1, 2, 3, 4], dtype=int32)

In [14]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print('Matrix1 shape', matrix1.shape)
print('Matrix2 shape', matrix2.shape)
print(tf.matmul(matrix1, matrix2).eval(session=tf.Session())) # 이렇게 matrix 곱하기를 해야 제대로 된 결과가 나오지
(matrix1 * matrix2).eval(session=tf.Session()) # 이렇게 잘못 곱하면 잘못된 결과가 나온다

Matrix1 shape (2, 2)
Matrix2 shape (2, 1)
[[ 5.]
 [11.]]


array([[1., 2.],
       [6., 8.]], dtype=float32)

In [15]:
# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval(session=tf.Session())

array([[5., 5.]], dtype=float32)

In [16]:
# Broadcasting: shape이 다르더라도 연산을 할 수 있게 해주는, 잘 모르고 사용 시 예상치 못한 결과를 낼 수 있기 때문에 사용할 때 주의해야 함
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval(session=tf.Session())

array([[4., 5.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval(session=tf.Session())

array([[4., 6.]], dtype=float32)

In [19]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval(session=tf.Session())

array([[4., 5.],
       [5., 6.]], dtype=float32)

In [20]:
# reduce_mean: 행렬에서 값이 여러 개 있는데 그것을 하나로(평균으로) 줄이고 싶다
tf.reduce_mean([1, 2], axis=0).eval(session=tf.Session()) # int, float인지 주의해야 한다

1

In [22]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval(session=tf.Session()) # 10 / 4

2.5

In [23]:
# Axis 학습
tf.reduce_mean(x, axis=0).eval(session=tf.Session()) # 1, 3 | 2, 4 (세로)

array([2., 3.], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=1).eval(session=tf.Session()) # 1, 2 | 3, 4 (가로)

array([1.5, 3.5], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=-1).eval(session=tf.Session()) # 가장 안쪽에 있는 것을 평균 내어라 1, 2 | 3, 4

array([1.5, 3.5], dtype=float32)

In [26]:
# reduce_sum
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=tf.Session()) # 1 + 2 | 3 + 4 둘의 합 / 2

5.0

In [28]:
# argmax 가장 큰 값의 index 구하기
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval(session=tf.Session()) # 0[0], 2[1] | 1[0], 1[1] | 2[0], 0[1]

array([1, 0, 0])

In [29]:
tf.argmax(x, axis=1).eval(session=tf.Session()) # 0, 1, 2 | 2, 1, 0

array([2, 0])

In [30]:
# reshape
t = np.array([[[0, 1, 2],
               [3, 4, 5]], 
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [31]:
tf.reshape(t, shape=[-1, 3]).eval(session=tf.Session()) # 안에거는 3, 나머지는 알아서 하기(-1): RANK를 줄이기
# 보통 가장 안의 갯수(3)은 잘 건드리지 않고 나머지를 건드리게 되므로 그렇게 심하게 변화가 있지는 않아서 데이터가 맘대로 바뀔까 걱정은 덜어도 된다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=tf.Session()) # rank를 늘이기

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [33]:
# reshape(squeeze, expand)
tf.squeeze([[0], [1], [2]]).eval(session=tf.Session()) # 쪼그라뜨리기

array([0, 1, 2], dtype=int32)

In [34]:
tf.expand_dims([0, 1, 2], 1).eval(session=tf.Session()) # 늘리기

array([[0],
       [1],
       [2]], dtype=int32)

In [35]:
# One hot: [0, 1, 2, 3, 4, 5]의 인덱스가 있으면 [0, 0, 0, 1, 0, 0]으로 3만 on 되어 있다는 것을 나타내도록 바꿔주는 함수
# rank을 하나 더 늘려주게 된다 2->3
# 그게 싫으면 reshape해주면 됨
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=tf.Session()) # depth: total 인덱스가 어디까지 있는지

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [37]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=tf.Session())

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [40]:
# casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=tf.Session()) # float to int

array([1, 2, 3, 4], dtype=int32)

In [41]:
tf.cast([True, False, 1==1, 0==1], tf.int32).eval(session=tf.Session()) # boolean to int

array([1, 0, 1, 0], dtype=int32)

In [42]:
# stack: 쌓는다
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dimension
tf.stack([x, y, z]).eval(session=tf.Session())

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [43]:
tf.stack([x, y, z], axis=1).eval(session=tf.Session())

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [44]:
tf.stack([x, y, z], axis=0).eval(session=tf.Session())

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [45]:
tf.stack([x, y, z], axis=-1).eval(session=tf.Session())

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [46]:
# ones and zeros like
x = [[0, 1, 2], 
     [2, 1, 0]]
tf.ones_like(x).eval(session=tf.Session()) # shape이 똑같은, 1로 채워진 tensor을 만들고 싶다

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [47]:
tf.zeros_like(x).eval(session=tf.Session()) # shape이 같은, 0으로 채워진 tensor을 만들고 싶다

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [48]:
# zip 복수의 배열을 한방에
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [49]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
