In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [3]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 3], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [4]:
X = tf.placeholder('float', [None, 3])
Y = tf.placeholder('float', [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [5]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [6]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [7]:
# Launch graph
with tf.Session() as sess:
    #Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict = {X: x_data, Y: y_data}) # training data만 이용해서 학습한다
        print(step, cost_val, W_val)
        
    # predict
    print('Prediction: ', sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print('Accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test})) # accuracy test할 때에는 test data를 사용

0 3.485527 [[ 1.8361298   0.28866884 -0.6931517 ]
 [-0.07524608 -0.9822159   0.137582  ]
 [ 0.13980237  1.2218037  -1.3267696 ]]
1 2.9810047 [[ 1.7976737   0.28983733 -0.65586406]
 [-0.20352015 -0.9534601   0.23710027]
 [ 0.04674102  1.2276367  -1.2395413 ]]
2 2.6513586 [[ 1.7814702   0.2690283  -0.6188515 ]
 [-0.21257065 -1.0432125   0.3359032 ]
 [ 0.06966922  1.1179149  -1.1527476 ]]
3 2.3276434 [[ 1.7481475e+00  2.6570040e-01 -5.8220083e-01]
 [-3.1457776e-01 -1.0388610e+00  4.3355879e-01]
 [ 1.4647618e-03  1.1001005e+00 -1.0667287e+00]]
4 2.0256019 [[ 1.729984    0.24855126 -0.54688823]
 [-0.33639702 -1.1092077   0.5257247 ]
 [ 0.00996185  1.0094434  -0.98456866]]
5 1.7590647 [[ 1.7018447   0.2442352  -0.51443285]
 [-0.4123645  -1.110603    0.6030874 ]
 [-0.03783889  0.9862942  -0.9136187 ]]
6 1.5961517 [[ 1.6878775   0.23335595 -0.48958647]
 [-0.41151717 -1.1458488   0.6374859 ]
 [-0.01742046  0.928039   -0.8757819 ]]
7 1.5405421 [[ 1.6684743   0.23280942 -0.46963674]
 [-0.4380291 

149 0.7124561 [[ 0.34386623  0.01154367  1.0762376 ]
 [-0.24325663 -0.43400154 -0.2426213 ]
 [ 0.26843774  0.3053898  -0.5389907 ]]
150 0.7107653 [[ 0.33795783  0.01097971  1.0827099 ]
 [-0.24185742 -0.4326203  -0.24540174]
 [ 0.26933342  0.30442813 -0.5389247 ]]
151 0.70909464 [[ 0.33207577  0.01042724  1.0891445 ]
 [-0.24047755 -0.43126148 -0.24814044]
 [ 0.27023974  0.30348587 -0.53888875]]
152 0.7074438 [[ 0.3262198   0.00988612  1.0955416 ]
 [-0.2391167  -0.4299248  -0.25083795]
 [ 0.2711567   0.3025625  -0.5388824 ]]
153 0.70581234 [[ 0.3203896   0.00935626  1.1019017 ]
 [-0.23777483 -0.42860976 -0.25349483]
 [ 0.27208403  0.30165777 -0.53890496]]
154 0.70419985 [[ 0.3145849   0.00883753  1.1082251 ]
 [-0.23645167 -0.42731613 -0.25611162]
 [ 0.2730217   0.30077112 -0.538956  ]]
155 0.70260614 [[ 0.30880547  0.00832983  1.1145123 ]
 [-0.23514709 -0.42604342 -0.25868893]
 [ 0.2739695   0.2999023  -0.53903496]]
156 0.7010306 [[ 0.30305097  0.00783302  1.1207637 ]
 [-0.23386082 -0.42