In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [12]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [13]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 3], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [14]:
X = tf.placeholder('float', [None, 3])
Y = tf.placeholder('float', [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [15]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost) # Learning rate을 크게 줘 보았다 -> cost의 변화가 너무 작다

In [16]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [17]:
# Launch graph
with tf.Session() as sess:
    #Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict = {X: x_data, Y: y_data}) # training data만 이용해서 학습한다
        print(step, cost_val, W_val)
        
    # predict
    print('Prediction: ', sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print('Accuracy: ', sess.run(accuracy, feed_dict={X: x_test, Y: y_test})) # accuracy test할 때에는 test data를 사용

0 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
1 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
2 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
3 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
4 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
5 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
6 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
7 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.536

181 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
182 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
183 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
184 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
185 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
186 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
187 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18623123]
 [-0.5367362   0.43353838  0.33472735]]
188 6.067981 [[ 1.2108424   0.9373808  -0.18306702]
 [-0.75659686  0.9006615   0.18