In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
# One hot encoding -> [0, 0, 1] 이면 2를 의미하고, [1, 0, 0]이면 0, [0, 1, 0] 이면 1

In [3]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3]) # label의 갯수 3
nb_classes = 3 # 즉, class의 갯수 3이 

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') # 4 * 3
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [4]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [5]:
# Cross entropy cost/Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [8]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
    # testing & one-hot encoding
    a = sess.run(hypothesis, feed_dict = {X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(a, sess.run(tf.arg_max(a, 1)))

0 5.4118714
200 0.57908976
400 0.4724341
600 0.3943271
800 0.32200688
1000 0.25150558
1200 0.22362104
1400 0.20357114
1600 0.18670505
1800 0.17232674
2000 0.15993166
[[6.5458762e-03 9.9344528e-01 8.8435672e-06]
 [8.4794164e-01 1.4080136e-01 1.1257019e-02]
 [1.6464437e-08 3.6533078e-04 9.9963462e-01]] [1 0 2]
